const SET_USER = 'SET_USER';
const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
const UNLOG_USER = 'UNLOG_USER';
const USER_AUTH_FAILED = 'USER_AUTH_FAILED';

export { SET_USER, USER_PROFILE_LOADING, UNLOG_USER, USER_AUTH_FAILED };
